### ISSUE TITLE
Plugin Review Comments

### ISSUE THREAD

**Issue by jneilliii** [cmuche/octoprint-timelapseplus#23]
self._plugin_data needs to be replaced.

> Plugins should not access this property directly but instead utilize [get_plugin_data_folder()](https://docs.octoprint.org/en/master/modules/plugin.html#octoprint.plugin.types.OctoPrintPlugin.get_plugin_data_folder)

use elif in comparison chain to avoid additional processing
https://github.com/cmuche/octoprint-timelapseplus/blob/e7291cce7fe591f84c0f1f2e4217eea5aac9c2bf/octoprint_timelapseplus/__init__.py#L346-L367

Need to include a software update hook so that future updates to the plugin can be automatically distributed to your users. You can find additional information from [here](https://docs.octoprint.org/en/master/bundledplugins/softwareupdate.html#hooks). 

As it relates to this you will also need to create a release with tag that matches the current plugin version defined in setup.py. 

I can't tell from the workflow exactly, but if a new print is started during the rendering process does your plugin pause/cancel the rendering? 

All threads need to have daemon=True set in order to avoid a situation where a restart of OctoPrint is blocked.

**Comment by cmuche** [comment]
Hi @jneilliii and first of all thank you for your detailled input.
I'm gonna work on these issues and get back to you soon!

**Comment by cmuche** [comment]
Hi @jneilliii
I just fixed the code according to your comments: https://github.com/cmuche/octoprint-timelapseplus/pull/25
Can you maybe verify the update hook in particular? Hope this is implemented correctly. I also created a release for the 1.0.0 version.

> I can't tell from the workflow exactly, but if a new print is started during the rendering process does your plugin pause/cancel the rendering?

No, the rendering is not paused or cancelled when a new print starts since it can run in parallel (at least tested on my host machine). Do you mention that because it could potentially cause trouble on e.g. a Raspberry Pi?

**Comment by jneilliii** [comment]
> Do you mention that because it could potentially cause trouble on e.g. a Raspberry Pi?

Yes, it is a bit of a concern because of the computational requirements of rendering video. I'm not sure if the built-in timelapse or OctoLapse takes this into account or not, but I vaguely remember they do. Will have to double-check.

**Comment by cmuche** [comment]
Okay - I'd also have to check if Timelapse or OctoLapse check for parallel prints/renderings but an idea would be to 1) put a prompt before starting a render job if a print is running and 2) display a promt when a print is started (should be possible to block the starting print since OctoLapse does this for its preview feature). I'll definitely include it in my features backlog.

**Comment by jneilliii** [comment]
as for the software update and all the other changes, everything looks good.

**Comment by cmuche** [comment]
Great! Thank you for your effort and helpful comments!
