### ISSUE TITLE
force capturing to bypass error checking and re-check when a print starts

### ISSUE THREAD

**Issue by pracovnik** [cmuche/octoprint-timelapseplus#49]
I have setup Octoprint events (PrintStarted, PrintDone  and PrintFailed), to (auto) start or stop web-camera service (by default is off) during printing.
Sadly, Timelapse+ detects the web camera (snapshot or stream) as not working and gives up on whole recording. So I end up with no snapshots/photoes during whole printing time. Octolapse and Timelapse works good.

URL for snapshot is copied from Timelapse, so I do not think there is an issue (mjpg-streamer)

_Error:
Hmm, something isn't working properly. Please fix the following error so Timelapse+ can run. Open the settings page to edit or fix the configuration.
Could not retrieve Webcam Snapshot_

**Comment by cmuche** [comment]
Hi @pracovnik and thank you for your input!
Okay - I see that could be problematic in your case because Timelapse+ re-checks the settings when they are changed and disables itself when a print job is started but there are errors with the capturing. In 1.2.0 there will also be a Re-Check button but that won't fix the problem you have. So a possible solution would be to check the settings again when a print job is started. I'll implement that ans also release it with the 1.2.0 version very soon. But I guess that your camera is not available instant, so imho a 'Force Capturing' option would be suitable to fix your problems which doesn't block the capturing progress when there are errors. Would that maybe fix your problems? This solution could then also be included in the next version.

**Comment by pracovnik** [comment]
No hurry... was just interested to see how better is your solution-plugin compared to existing one. I have seen few people mentioned the same way as I do with the on-off camera, so had an urge to write it as an issue...

**Comment by cmuche** [comment]
Hey @pracovnik 
Those features are now added (checking before print and the force capturing option).
Could you maybe test if it's now working on your setup? You cann install the pre-released version with this url:

https://github.com/cmuche/octoprint-timelapseplus/archive/f201ebd8140638e77b6ab2e45ad1f75556cf6a6a.zip

![image](https://github.com/cmuche/octoprint-timelapseplus/assets/14235338/71b416ed-2dc2-4fed-a139-2a79b624c26b)

Then I'd include it in the next version very soon. I really appreciate your feedback! Thank you!
