### ISSUE TITLE
Octopi - 1.9.0 correct h.264 Webcam URL?

### ISSUE THREAD

**Issue by jDavidnet** [cmuche/octoprint-timelapseplus#81]
I have Octoprint running as an upgraded 1.9.0 Octopi server on a Raspberry Pi 4.

With the release of 1.9.0, I thought it would be neat to fully switch over to h.264 since the Pi4 has a built-in h.264 encoder, and, as I understand it, the pi webcam supports h.264 streaming.

If it's not possible yet, fine, no rush, but what is the correct URL if it is possible?
The one for jpeg capture doesn't seem correct.

**Comment by cmuche** [comment]
Hi @jDavidnet 
As I experienced while testing, using a (H.264) stream is not the ideal solution for capturing snapshots since the transcoding takes some time (maybe not that long on a Pi 4, but still some ms) and it has be done by Timelapse+ itself. So that could influence the timing of the snapshot capturing. A still frame (jpg) source would probably the better choice. To be honest I don't know what the exact stream/snapshot URLs are for OctoPi, but I guess it should be somewhere in its documentation.

**Comment by cmuche** [comment]
Did this solve your problem?

**Comment by jDavidnet** [comment]
Honestly, it seemed like maybe I should just stick with the default webcam stuff for now, and I uninstalled the plugin while 1.9.0 and other things kinda settle.

**Comment by cmuche** [comment]
Okay - that's sad. But may I ask if Timelapse+ didn't work for you? It has the possibility to capture from H264 MP4 streams. Is there an issue with OctoPrint 1.9.0? AFAIK there are also no Webcam Plugins available and the 'Classic Webcam' plugin behaves like the old webcam functionality (still JPEG snapshot).

**Comment by jDavidnet** [comment]
I am fairly time-limited, and I didn't want to debug it or think it through.  There are two primary concerns I have with Octoprint/video.  
1.) Video latency for streaming so I can detect problems earlier
2.) Some sort of system resources issue that makes my VERY FAST computer slow until I refresh the page.

I'd like to first resolve those two above issues.

Future video concerns:
* I have to flip and rotate my video
  * my pi webcam is tilted vertically at the moment; maybe this is causing an issue with the default webcam streaming
* I'd like to get away from JPEG capture
  * it seems CPU intensive and not very efficient ( I understand that for time-lapses, it might not matter at all, but the real-time video is different )
* I'd like to have a model print cam and a nozzle cam
  * Modelcam:
    * Timelapse
    * Streaming ( AI and Human Monitoring)
  * Nozzlecam
    * Streaming ( AI and Human Monitoring)
    
I honestly didn't integrate Timelapse+ into my workflow at all yet. I realized that 1.9.0 was a huge architecture shift for Video, and information on the web was very limited on how 1.9.0 would work with various plugins, especially video plugins, so I just didn't want to risk any extra stability, so I uninstalled a few video plugins that I didn't need.  I also wasn't sure yet how Timelapse+ would improve or change anything over the default video plugins or Octolapse, so I didn't see the value in playing with something unproven, risky, and ontop of that, I was unsure how it interacted with 1.9.0.

If you had a test matrix on the github page that showed that it worked with 1.8.x and 1.9.0, and some language discussing how it worked on 1.8.x. and what changes were made to work with 1.9.0 that would go a long way to build confidence in the plugin.

A feature matrix comparing this plugin to the default and to competitors would be cool too.

It would also be nice to know which other video plugins this plugin complement each other and which ones it's tested with.

**Comment by cmuche** [comment]
First of all thank you for your detailed answer.

Timelapse+ doesn't rely on any webcam support or settings in OctoPrint itself. OctoPrint didn't have Webcam support itself but handled video input and snapshot capturing (for the integrated stock Timelapse feature) via external URLs. OctoPi as well as the docker image are bundled with webcam streaming services that OctoPrint can use. And so does Timelapse+. So there is/was no need to update the plugin in order to make it work in 1.9.0. As I understand correctly, there is now the possibility for plugins to implement different camera APIs directly in OctoPrint. This could be a feature for Timelapse+ to use these in the future. But currently Timelapse+ doesn't have any other plugins as dependencies and doesn't affect other plugins. Until then, the snapshot capturing works fine as it currently does. So Timelapse+ doesn't change/manipulate/implement any camera support in OctoPrint, it just reads from an external camera service. Exactly as other plugins and OctoPrint itself.

You can take a look at [the Wiki](https://github.com/cmuche/octoprint-timelapseplus/wiki), it describes how Timelapse+ works.

While printing it just fetches and saves the captured snapshots. This isn't a costly process and doesn't really affect the performance of OctoPrint.

I hope I could help you with these information. Just let me know if you have further questions or concerns.

**Comment by cmuche** [comment]
FYI: Timelapse+ now support the new Webcam Plugins in OctoPrint 1.9.0.
Please let me know if you need more information, if not I'd close this issue.
